plugins {
	id 'fabric-loom' version '1.16.3'
	id 'maven-publish'
}

base {
	archivesName = project.archives_base_name
}
version = project.mod_version
group = project.maven_group

repositories {
	mavenCentral()
}

dependencies {
    include(modImplementation('io.netty:netty-handler-proxy:4.1.82.Final'))
    include(modImplementation('io.netty:netty-codec-socks:4.1.82.Final'))

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
    runs {
        client {
            vmArgs "-Xms2G", "-Xmx2G", "-XX:MaxDirectMemorySize=2048m"
            programArgs "--width", "800", "--height", "600"
        }

		clientAlt {
            inherit client
            name "Client Alt"
            runDir "run-alt"
        }
    }
}

processResources {
    inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

jar {
    from("LICENSE") {
	rename { "${it}_${project.archives_base_name}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifact(remapJar) {
				builtBy remapJar
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	repositories {

	}
}
